services:    
  mongo:
      image: mongo:8.0
      restart: unless-stopped
      volumes:
        - ./data/mongo:/data/db
      ports:
          - "27017:27017"
  
  app:
    container_name: "app"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DATABASE: test_database
    depends_on:
      - mongo
    restart: unless-stopped
    ports:
      - "8000:8000"